spring:
  application:
    name: LocalBankApp

  datasource:
    url: jdbc:postgresql://postgres:5432/local_bank_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: bankapp.log

app:
  jwtSecret: my-very-secret-key-12345
  jwtExpirationMs: 86400000